[package]
name = "sol2zinc"
version = "0.1.0"
authors = ["Dmitry Borisenkov <dmitry.borisenkov89@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
rand = "0.8.2"
