[package]
name = "yul-compiler"
version = "0.1.0"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
    "Dmitry Borisenkov <dmitry.borisenkov89@gmail.com>",
]
license = "Apache-2.0"
edition = "2018"
description = "The YUL to LLVM compiler"

[[bin]]
name = "yulc"
path = "src/yulc/main.rs"

[dependencies]
structopt = { version = "0.3", default-features = false }
colored = "2.0"

rand = "0.8"
regex = "1.5"

compiler-const = { git = "ssh://git@github.com/matter-labs/compiler-const", branch = "main" }

[dependencies.inkwell]
git = "ssh://git@github.com/matter-labs-forks/inkwell"
branch = "master"
default-features = false
features = ["llvm11-0", "target-syncvm"]

[dependencies.zkevm-assembly]
git = "ssh://git@github.com/matter-labs/zkEVM-assembly"
branch = "main"
