[package]
name = "yul-compiler"
version = "0.1.0"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
    "Dmitry Borisenkov <dmitry.borisenkov89@gmail.com>",
]
edition = "2018"
description = "The YUL to LLVM compiler"

[[bin]]
name = "yul-compiler"
path = "src/yul-compiler/main.rs"

[dependencies]
structopt = { version = "0.3", default-features = false }
colored = "2.0"

rand = "0.8"
regex = "1.4"

rayon = "1.5"

[dependencies.inkwell]
git = "https://github.com/matter-labs-forks/inkwell"
branch = "master"
default-features = false
features = ["llvm11-0", "target-syncvm"]
