[package]
name = "sol2zinc"
version = "0.1.0"
authors = ["Dmitry Borisenkov <dmitry.borisenkov89@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3", default-features = false }
rand = "0.8.2"
regex = "1.4.3"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm10-0"] }
rayon = "1.5"
colored = "2.0"

[[bin]]
name = "sol2zinc"
path = "src/main.rs"

[[bin]]
name = "sol2zinc-test"
path = "src/tester/main.rs"
